In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

2023-05-19 14:54:23.836125: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
movie_reviews = ['amazing movie',
        'amazing screenplay',
        'so good to watch',
        'will watch again',
        'hard to digest',
        'do not watch with family',
        'horrible action',
        'poor quality',
        'just loved it!',
        'bad acting']

feedback = np.array([1,1,1,1,0,0,0,0,0,0])


In [10]:
a = np.array(movie_reviews)
np.unique(a.flatten())


10

In [14]:
vocab_size = 25
encoded_reviews = [one_hot(d, vocab_size) for d in movie_reviews]
print(encoded_reviews)

[[23, 19], [23, 11], [12, 24, 22, 13], [7, 13, 18], [6, 22, 17], [7, 6, 13, 6, 6], [18, 16], [5, 9], [20, 1, 12], [15, 3]]


In [15]:
max_length = 5
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[23 19  0  0  0]
 [23 11  0  0  0]
 [12 24 22 13  0]
 [ 7 13 18  0  0]
 [ 6 22 17  0  0]
 [ 7  6 13  6  6]
 [18 16  0  0  0]
 [ 5  9  0  0  0]
 [20  1 12  0  0]
 [15  3  0  0  0]]


In [16]:
embeded_vector_size = 10

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [17]:
X = padded_reviews
y = feedback

In [18]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 10)             250       
                                                                 
 flatten (Flatten)           (None, 50)                0         
                                                                 
 dense (Dense)               (None, 1)                 51        
                                                                 
Total params: 301
Trainable params: 301
Non-trainable params: 0
_________________________________________________________________
None


In [19]:
model.fit(X, y, epochs=50, verbose=0)


In [20]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 134ms/step - loss: 0.5897 - accuracy: 1.0000


1.0

In [21]:
weights = model.get_layer('embedding').get_weights()[0]
weights

array([[ 0.0063487 , -0.05948115, -0.06647543, -0.00206955,  0.07662971,
         0.00430162, -0.00089939,  0.08285811,  0.04659643, -0.07417975],
       [-0.0986698 ,  0.0581788 , -0.10036638, -0.05880994,  0.08563414,
        -0.0984487 , -0.07154179,  0.08499292, -0.0377113 , -0.04479944],
       [-0.04555628, -0.03702503, -0.03543254,  0.03688068,  0.00561578,
         0.01061964, -0.04133021, -0.01988447,  0.04424747,  0.03982176],
       [-0.06262188,  0.00475178, -0.03698746, -0.01355573,  0.07941059,
        -0.02673383, -0.02146895,  0.09054885, -0.02286593, -0.06888851],
       [-0.03399146, -0.04780308,  0.03260472,  0.01497864, -0.03372262,
        -0.03688998,  0.00098555, -0.02488532,  0.03831801,  0.02313867],
       [-0.0740354 ,  0.00071683,  0.0185373 , -0.03180682,  0.02955516,
         0.04698355, -0.03535455, -0.06004008,  0.08883809, -0.10765298],
       [-0.04153438,  0.06593198, -0.0159052 , -0.04536909, -0.07148987,
        -0.07555617, -0.01774289,  0.08825211