In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

2023-05-19 14:54:23.836125: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
movie_reviews = ['amazing movie',
        'amazing screenplay',
        'so good to watch',
        'will watch again',
        'hard to digest',
        'do not watch with family',
        'horrible action',
        'poor quality',
        'just loved it!',
        'bad acting']

feedback = np.array([1,1,1,1,0,0,0,0,0,0])


In [10]:
a = np.array(movie_reviews)
np.unique(a.flatten())


10

In [12]:
vocab_size = 45
encoded_reviews = [one_hot(d, vocab_size) for d in movie_reviews]
print(encoded_reviews)

[[15, 31], [15, 43], [32, 44, 22, 13], [43, 13, 38], [22, 22, 9], [19, 42, 13, 42, 18], [18, 4], [9, 33], [36, 33, 4], [39, 27]]


In [13]:
max_length = 5
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[15 31  0  0  0]
 [15 43  0  0  0]
 [32 44 22 13  0]
 [43 13 38  0  0]
 [22 22  9  0  0]
 [19 42 13 42 18]
 [18  4  0  0  0]
 [ 9 33  0  0  0]
 [36 33  4  0  0]
 [39 27  0  0  0]]
